# Generated by Django 2.2.3 on 2019-07-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-is_answer', '-timestamp'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='value',
        ),
        migrations.AlterField(
            model_name='question',
            name='has_answer',
            field=models.BooleanField(default=False),
        ),
    ]
